# Generated by Django 3.0.6 on 2020-05-05 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carslist',
            options={'verbose_name': 'Car', 'verbose_name_plural': 'Cars'},
        ),
        migrations.CreateModel(
            name='ModelInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('make', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=200)),
                ('drivetrain', models.CharField(max_length=3)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.CarsList')),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Models',
            },
        ),
    ]
